development:
  host: localhost
  database: ios_plague_development

test:
  host: localhost
  database: ios_plague_test

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOHQ_URL'] %>
